# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "uas" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.swraid.enable = true;
  services.lvm.boot.thin.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/78fba052-31c4-4417-8626-8759e0e6d110";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5F2C-095C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data/main" =  
    { device = "/dev/disk/by-uuid/2180fd7f-e6c5-4adb-82ee-79d99a8bba50";
      fsType = "btrfs";
      options = [    
        "defaults"
        "rw"
        "noatime"
        # "compress=zlib"  # ou "compress=lzo" selon vos préférences
        "autodefrag"
        # "nofail" 
      ];
    };

  fileSystems."/data/2" =  
   { device = "/dev/disk/by-uuid/13e22e4c-581c-449b-a1a3-b4ba6e853647";
    # fsType = "ext4";
     options = [    
       "defaults"
       "rw"
     ];
   };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ea11c9c0-aeea-4eb1-b4ed-37eb9d4b475e"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
