server:
  address: 'tcp://127.0.0.1:9091'

log:
  level: 'info'
  format: 'json'
  file_path: '#VARSPATH#/authelia.log'
  keep_stdout: true
totp:
  issuer: '#HOSTNAME#'

access_control:
  default_policy: one_factor
  rules:
    - domain: authelia#HOSTNAME#.
      policy: bypass
    - domain: log.#HOSTNAME#
      policy: one_factor
      subject: "group:admin"
    - domain: '*.#HOSTNAME#'
      policy: one_factor
definitions:
  user_attributes:
    immich_role:
      expression: '"admin" in groups ? "admin" : "user"'
    grafana_role:
      expression: '"admin" in groups ? "Admin" : "Viewer"'
authentication_backend:
  ldap:
    address: 'ldaps://ldap.#HOSTNAME#'
    implementation: 'custom'
    timeout: '5s'
    start_tls: false
    tls:
      server_name: 'ldap.#HOSTNAME#'
      skip_verify: true
      minimum_version: 'TLS1.2'
    base_dn: '#BASEDN#'
    additional_users_dn: 'ou=users'
    users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))'
    additional_groups_dn: 'ou=groups'
    groups_filter: '(&(member=cn={input},ou=users,#BASEDN#)(objectClass=groupOfNames))'
    user: 'cn=admin,#BASEDN#'
    attributes:
      # identifier: 'uid'
      distinguished_name: 'distinguishedName'
      username: 'cn'
      mail: 'mail'
      member_of: 'memberOf'
      group_name: 'cn'
session:
  cookies:
    - name: 'authelia_session'
      domain: '#HOSTNAME#'  # Should match whatever your root protected domain is
      authelia_url: 'https://authelia.#HOSTNAME#'
      expiration: '1 hour'
      inactivity: '5 minutes'

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  local:
    path: '#VARSPATH#/db.sqlite3'      
notifier:
  disable_startup_check: false
  filesystem:
    filename: '#VARSPATH#/notification.txt'
identity_providers:
  oidc:
    jwks:
      - key_id: 'nas'
        algorithm: 'RS256'
        use: 'sig'
        key: |- {{- fileContent "#PATHKEY#/authelia/private_key.pem" | nindent 10 }}
    enable_client_debug_messages: false
    minimum_parameter_entropy: 8
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_jwt_access_token_stateless_introspection: false
    discovery_signed_response_alg: 'none'
    discovery_signed_response_key_id: ''
    require_pushed_authorization_requests: false
    authorization_policies:
      policy_name:
        default_policy: 'one_factor'
        rules:
          - policy: 'deny'
            subject: 'group:services'
      grafana_admin:
        default_policy: 'deny'
        rules:
          - policy: 'one_factor'
            subject: 'group:admin'
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
      allowed_origins:
        - 'https://#HOSTNAME#'
      allowed_origins_from_client_redirect_uris: false
    claims_policies:
      immich_policy:
        custom_claims:
          immich_role:
            attribute: 'immich_role'
      grafana_policy:
        custom_claims:
          grafana_role:
            attribute: 'grafana_role'
    scopes:
      immich_scope:
        claims:
          - 'immich_role'
      grafana_scope:
        claims:
          - 'grafana_role'
  ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
  ## See: https://www.authelia.com/c/oidc
    clients:
      - client_id: 'nextcloud'
        client_name: 'NextCloud'
        client_secret: {{ fileContent "#PATHSECRET#/authelia/oicd_nextcloud_secret" | trimAll "\n" | trim | quote }} 
        public: false
        authorization_policy: 'one_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://nc.#HOSTNAME#/apps/user_oidc/code'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
          - 'nextcloud_userinfo'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'
      - client_id: 'immich'
        client_name: 'Immich'
        client_secret: {{ fileContent "#PATHSECRET#/authelia/oicd_immich_secret" | trimAll "\n" | trim | quote }}
        public: false
        authorization_policy: 'one_factor'
        require_pkce: false
        pkce_challenge_method: ''
        redirect_uris:
          - 'https://immich.#HOSTNAME#/auth/login'
          - 'https://immich.#HOSTNAME#/api/oauth/mobile-redirect'
          - 'app.immich:///oauth-callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
          - 'immich_scope'
        claims_policy: 'immich_policy'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'
      - client_id: 'grafana'
        client_name: 'Grafana'
        client_secret: {{ fileContent "#PATHSECRET#/authelia/oicd_grafana_secret" | trimAll "\n" | trim | quote }}
        public: false
        authorization_policy: 'grafana_admin'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://log.#HOSTNAME#/login/generic_oauth'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
          - 'grafana_scope'
        claims_policy: 'grafana_policy'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'
